# Load environment variables from the .env file
from dotenv import load_dotenv

# Import Hugging Face model integration
from langchain_huggingface import (
    HuggingFaceEndpoint,
    ChatHuggingFace
)

# Import ChatPromptTemplate
from langchain_core.prompts import ChatPromptTemplate


# Load environment variables
load_dotenv()


# --------------------------------------------------
# STEP 1: Create Hugging Face model
# --------------------------------------------------

# Connect LangChain with the Hugging Face API
llm = HuggingFaceEndpoint(
    repo_id="Qwen/Qwen2.5-7B-Instruct",
    task="text-generation",
    max_new_tokens=200,
    temperature=0.7,
)


# Convert the endpoint into a chat model
model = ChatHuggingFace(
    llm=llm
)


# --------------------------------------------------
# STEP 2: Create the first prompt
# --------------------------------------------------

# Prompt 1 asks the model to explain a topic
prompt_1 = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are a helpful technical teacher. "
            "Explain concepts in simple language."
        ),
        (
            "human",
            "Explain {topic} in simple words with one example."
        ),
    ]
)


# --------------------------------------------------
# STEP 3: Create the second prompt
# --------------------------------------------------

# Prompt 2 will receive the output of Prompt 1
prompt_2 = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are a technical content writer."
        ),
        (
            "human",
            "Create a short summary of the following explanation "
            "in 3 bullet points:\n\n{explanation}"
        ),
    ]
)


# --------------------------------------------------
# STEP 4: Create Chain 1
# --------------------------------------------------

# First chain:
#
# Input → Prompt 1 → Model
#
chain_1 = prompt_1 | model


# --------------------------------------------------
# STEP 5: Create Chain 2
# --------------------------------------------------

# Second chain:
#
# Explanation → Prompt 2 → Model
#
chain_2 = prompt_2 | model


# --------------------------------------------------
# STEP 6: Run the first chain
# --------------------------------------------------

first_response = chain_1.invoke(
    {
        "topic": "LangChain"
    }
)


# Extract the text generated by the model
explanation = first_response.content


# Display the first response
print("=" * 60)
print("STEP 1 - EXPLANATION")
print("=" * 60)

print(explanation)


# --------------------------------------------------
# STEP 7: Pass Chain 1 output into Chain 2
# --------------------------------------------------

second_response = chain_2.invoke(
    {
        "explanation": explanation
    }
)


# Extract the final response
summary = second_response.content


# --------------------------------------------------
# STEP 8: Display the final result
# --------------------------------------------------

print("\n" + "=" * 60)
print("STEP 2 - SUMMARY")
print("=" * 60)

print(summary)